// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TheLastOfThem.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415130246_PruebaAnimales2")]
    partial class PruebaAnimales2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("api.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Amenazas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .HasColumnType("TEXT");

                    b.Property<string>("Especie")
                        .HasColumnType("TEXT");

                    b.Property<string>("Familia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .HasColumnType("TEXT");

                    b.Property<string>("Justificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCientifico")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreComun")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orden")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reino")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Animales");
                });
#pragma warning restore 612, 618
        }
    }
}
